variable "image_family" {
  type    = string
  default = "custom-images"
}

variable "image_name" {
  type    = string
  default = "custom-image-with-db"
}

variable "network" {
  type    = string
  default = "projects/cloud-nw-dev/global/networks/default"
}

variable "project_id" {
  type    = string
  default = "cloud-nw-dev"
}

variable "source_image_family" {
  type    = string
  default = "centos-stream-8"
}

variable "ssh_username" {
  type    = string
  default = "root"
}

variable "subnetwork" {
  type    = string
  default = "default"
}

variable "use_os_login" {
  type    = bool
  default = true
}

variable "zone" {
  type    = string
  default = "us-east1-c"
}
packer {
  required_plugins {
    googlecompute = {
      source  = "github.com/hashicorp/googlecompute"
      version = "~> 1"
    }
  }
}

source "googlecompute" "autogenerated_1" {
  image_family        = var.image_family
  image_name          = var.image_name
  network             = var.network
  project_id          = var.project_id
  source_image_family = var.source_image_family
  ssh_username        = var.ssh_username
  subnetwork          = var.subnetwork
  use_os_login        = var.use_os_login
  zone                = var.zone
}


build {
  sources = ["source.googlecompute.autogenerated_1"]

  provisioner "shell" {
    inline = [
      "ls -l"
    ]
  }
  provisioner "shell" {
    script = "./packer/group.sh"
  }

  provisioner "file" {
    destination = "/tmp/config.yml"
    source      = "./packer/config.yml"
  }
  
  provisioner "shell" {
    script = "./packer/ops_agent.sh"
  }

  provisioner "file" {
    destination = "/tmp/csye6225.service"
    source      = "./packer/csye6225.service"
  }
  
  provisioner "file" {
    destination = "/tmp/webapp-0.0.1-SNAPSHOT.jar"
    source      = "./webapp-artifact/webapp-0.0.1-SNAPSHOT.jar"
  }
  
  provisioner "shell" {
    script = "./packer/server.sh"
  }

  post-processor "manifest" {
    output = "./packer/image-manifest.json"
  }
}
