
# See https://www.packer.io/docs/templates/hcl_templates/blocks/packer for more info
packer {
  required_plugins {
    googlecompute = {
      source  = "github.com/hashicorp/googlecompute"
      version = "~> 1"
    }
  }
}

# source blocks are generated from your builders; a source can be referenced in
# build blocks. A build block runs provisioner and post-processors on a
# source. Read the documentation for source blocks here:
# https://www.packer.io/docs/templates/hcl_templates/blocks/source
source "googlecompute" "autogenerated_1" {
  image_family        = "custom-images"
  image_name          = "custom-image-with-db"
  network             = "projects/cloud-nw-dev/global/networks/default"
  project_id          = "cloud-nw-dev"
  source_image_family = "centos-stream-8"
  ssh_username        = "root"
  subnetwork          = "default"
  use_os_login        = true
  zone                = "us-east1-c"
}


# a build block invokes sources and runs provisioning steps on them. The
# documentation for build blocks can be found here:
# https://www.packer.io/docs/templates/hcl_templates/blocks/build
build {
  sources = ["source.googlecompute.autogenerated_1"]

  provisioner "shell" {
    inline = [
      "ls -l"
    ]
  }
  provisioner "shell" {
    script = "./packer/group.sh"
  }

  provisioner "shell" {
    script = "./packer/install_db.sh"
  }

  provisioner "file" {
    destination = "/tmp/csye6225.service"
    source      = "./packer/csye6225.service"
  }
  
    provisioner "file" {
    destination = "/usr/app/webapp-0.0.1-SNAPSHOT.jar"
    source      = "./webapp-0.0.1-SNAPSHOT.jar"
  }

  provisioner "shell" {
    script = "./packer/server.sh"
  }

  post-processor "manifest" {
    output = "./packer/image-manifest.json"
  }
}
